[package]
name = "bitcoin_ticket_platform"
version = "0.1.0"
edition = "2021"

[dependencies]
bdk = "0.30.1"
wasm-bindgen = "0.2.100"
bdk_esplora = "0.20.1"
getrandom = { version = "0.2.15", features = ["js"] }
idna = "=1.0.3"
openssl = "0.10.70"

[lib]
crate-type = ["cdylib"]

[dependencies.web-sys]
version = "0.3.77"
features = ["Window", "Document", "HtmlElement"]

